### ISSUE TITLE
TX2 장치에서 최대 몇개 모델을 동시에 서빙 할 수 있는 지 파악하기

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/tfserving-inference#24]
CNN, Object detection, NLP 모델 중 최대 몇개를 동시에 로드 및 서빙 할 수 있는지 분석

**Comment by kh3654po** [comment]
tx2 장비에 디스크 용량을 늘려서 모델을 테스트 해볼 예정입니다. xavier장비는 테스트 완료했습니다.

**Comment by kh3654po** [comment]
테스트해본 결과 mobilenet_v1, mobilenet_v2, inception_v3, yolo_v5까지는 로드가 되었지만 bert_imdb 모델을 로드할 때 메모리 부족으로 프로그램이 종료되었습니다.
테스트 환경은 xavier와 마찬가지로 메모리 제한을 줬고 제한은 8GB중 5GB로 줬습니다.

bert_imdb와 distilbert_sst2 모델을 돌려본결과 하나씩 로드할때는 잘작동했지만 두개를 동시에 로드할때는 마찬가지로 프로그램이 종료되었습니다.

결론적으로 여러모델을 로드할때는 mobilenet_v1, mobilenet_v2, inception_v3, yolo_v5가 가능하고
bert_imdb와 distilbert_sst2 모델은 하나씩만 가능합니다.

**Comment by hyu-leeky** [comment]
오케이. nlp 모델이 무거워서 다 올라가지 않는듯 하네. 잘 확인은 되었다. 하드웨어별로 지원되는 모델 셋들이 다른듯 하고, 이런 것들을 kubernetes 의 label 로 알리거나 해서 로드 밸런서 단에서 어떤 pod 로 어떤 요청을 보내면 될런지를 생각해볼 여지가 있겠다. 나노도 확인해보면서 같이 이야기 해보자.
