### ISSUE TITLE
모델 요청 시나리오 작성하기

### ISSUE THREAD

**Issue by kh3654po** [ddps-lab/tfserving-inference#30]
각 장비에 추론을 요청할 시나리오를 작성해본다. 이때 cnn, object detection, nlp 요청량을 다양하게 하여 작성한다.
예를 들어 cnn 요청량이 많은 경우, nlp 요청량이 많은 경우의 시나리오를 작성한다.

**Comment by hyu-leeky** [comment]
석현아. 워크로드 시나리오 만들때 참조용으로 기록해두면
- 통계적 모델에 기반한 워크로드 생성 (https://numpy.org/doc/stable/reference/random/generated/numpy.random.poisson.html)
- 트위터 워크로드를 활용한 시나리오 생성 (https://github.com/ddps-lab/research-issues/issues/119)

처음에 이야기한 통계적 모델이 조금 더 쉽게 시작할 수 있을것 같기는 해. 진행해보면 이슈 생기면 함께 논의해보자.

**Comment by kh3654po** [comment]
통계적 모델에 기반한 워크로드 생성을 시도해 봤습니다. 
model 1, model 2, model 3 모델이 있을 때 이 모델들의 요청을 생성하는 것을 예로 들겠습니다.

각 모델의 요청이 초당 몇씩 들어올지 결정을 합니다. (model 1 : 초당 10개, model 2 : 초당 2개, model 3 : 초당 3개)
얼마동안 요청을 보낼지 결정합니다. (총 5초) 
포아송 분포 생성 함수 (random.poisson(초당 몇개, 몇초동안 요청을 할지))를 이용하여 모델마다 포아송 분포를 생성합니다.

**Comment by kh3654po** [comment]
시나리오 작성 코드를 구현하여 초당 평균 15개의 요청을 발생시키는 시나리오를 작성. 이를 테스트해본결과 장비에 부하가 걸리지않아 실험에 쓰기에는 부적합하여 요청량을 늘려 부하가 걸리는 지점을 파악해야함

**Comment by hyu-leeky** [comment]
그래 석현아. 워크로드 늘려서 지금의 시간보다 확실히 오래 걸리는데도 일부 장비는 idle 인 경우가 발생하는지를 잘 파악해보자.

**Comment by kh3654po** [comment]
초당 평균 요청량이 아래와 같고
'mobilenet_v1': 20 
'mobilenet_v2': 2
'inception_v3': 2
'yolo_v5': 1

엣지장비별 모델로드 상황이 다음과 같을 때
'nvidia-xavier2': 'mobilenet_v1', 'mobilenet_v2', 'inception_v3', 'yolo_v5'
'nvidia-tx2': 'mobilenet_v1', 'mobilenet_v2', 'inception_v3', 'yolo_v5'
'nvidia-nano1': 'mobilenet_v2', 'inception_v3'

요청량의 대부분이 mobilenet_v1이지만 nano1에서는 mobilenet_v1이 로드되어있지않습니다.
요청마다 어느 장비에 요청했는지와 해당 시간을 기록하고 요청과 요청사이의 시간을 측정하였습니다.
결과는 다음과 같습니다. xavier2와 tx2는 평균 0.2초 간격마다 요청을 처리했지만 nano1은 평균 1.6초마다 처리했고 최대 5초정도 idle상태였습니다. 

```
# idle time by edge

[nvidia-xavier2] avg: 0.22083080924956905
[nvidia-xavier2] min: 0.05853700637817383
[nvidia-xavier2] max: 0.5569157600402832

[nvidia-tx2] avg: 0.22315375853557975
[nvidia-tx2] min: 0.05448198318481445
[nvidia-tx2] max: 0.6148147583007812

[nvidia-nano1] avg: 1.683226198985659
[nvidia-nano1] min: 0.2287580966949463
[nvidia-nano1] max: 4.98030424118042
```

**Comment by hyu-leeky** [comment]
오케이 석현아. 추가로 각 요청들의 처리 시간에 대해서 평균, 최소, 최대, 25%, 50%, 75% 요청이 처리된 시간을 알수 있을까?

**Comment by kh3654po** [comment]
다음과 같은 형식으로 실험을 진행하면 될까요?

total inference time 49.88910126686096

----------------------
inference time info (each argument is info about requests per sec)

[1] avg: 0.13847601413726807
[1] min: 0.06971979141235352
[1] max: 0.32680225372314453
[1] 25%: 0.1149756908416748
[1] 50%: 0.1251235008239746
[1] 75%: 0.18886327743530273

[2] avg: 0.21788754065831503
[2] min: 0.06256508827209473
[2] max: 0.7532820701599121
[2] 25%: 0.12036299705505371
[2] 50%: 0.19057679176330566
[2] 75%: 0.25220155715942383

[3] avg: 0.2400655174255371
[3] min: 0.11230993270874023
[3] max: 0.5753850936889648
[3] 25%: 0.18143701553344727
[3] 50%: 0.19918537139892578
[3] 75%: 0.2921576499938965

----------------------
idle time by edge

[nvidia-xavier2] avg: 0.21604246989540432
[nvidia-xavier2] min: 0.05386638641357422
[nvidia-xavier2] max: 0.5024049282073975
[nvidia-xavier2] 25%: 0.13909506797790527
[nvidia-xavier2] 50%: 0.19466280937194824
[nvidia-xavier2] 75%: 0.2603907585144043

[nvidia-tx2] avg: 0.21715349377247326
[nvidia-tx2] min: 0.05897164344787598
[nvidia-tx2] max: 0.49489927291870117
[nvidia-tx2] 25%: 0.1481776237487793
[nvidia-tx2] 50%: 0.19510602951049805
[nvidia-tx2] 75%: 0.2575099468231201

[nvidia-nano1] avg: 2.2972764843388607
[nvidia-nano1] min: 0.2538447380065918
[nvidia-nano1] max: 7.979926824569702
[nvidia-nano1] 25%: 1.149662971496582
[nvidia-nano1] 50%: 1.7291839122772217
[nvidia-nano1] 75%: 3.1011581420898438

**Comment by hyu-leeky** [comment]
석현아 위의 정보중에서 [1][2][3] 은 어떤걸 의미하는거야?
그리고 아래쪽의 각 장비의 이름이 [] 안에 있는건 각 장비에서 요청을 처리한 시간의 통계인것 같아.  잘 정리했어.
그런데 이게 idle time 은 아닌듯하고, idle time 을 알면 좋을것 같다는 생각이 들기는 한다. 혹시 전체 실험 시간 중 실제로 요청을 처리한 시간 혹은 cpu, gpu 등의 사용율을 알수 있을까? 해당 정보는 얻기가 쉽지는 않을테니 어렵다면 우선 배제해둬도 되겠다.

**Comment by kh3654po** [comment]
[1], [2], [3]은 second를 의미합니다. [1]은 타임라인에서 1초를 의미하고 [2]는 2초를 의미합니다. 각각의 초동안 들어온 요청들에 대한 정보입니다.
처음에 idle time은 cpu gpu 사용율로 하고자했으나 모니터링에 어려움이 있어서 요청시간 사이로 결정했는데 교수님 말씀처럼 정확한 idle time은 아닌거 같습니다. 다시 생각해봤는데 요청을 보낸시간에 요청을 처리한 시간을 더해서 따로 기록을하고 이 기록과 요청을 보낸 시간 정보를 가지고 idle time을 구하면 좀더 정확할거 같습니다.

**Comment by hyu-leeky** [comment]
응 오케이 석현아. 월요일에 만나서 더 이야기를 나눠보자.
