### ISSUE TITLE
tf serving을 통해 각각의 모델 serving 해보기

### ISSUE THREAD

**Issue by kh3654po** [ddps-lab/tfserving-inference#4]
현재 확인된 모델
- mobilenet_v1
추가적으로 확인해야할 모델
- mobilenet_v2
- inception_v3
- yolov5
- NLP
- RNN
- LSTM

Edge와 Cloud 공통으로 사용되는 부분입니다.

또한 bench 코드의 preprocessing 부분을 모델별로 각각 만들어야함 -> 현재는 mobilenet에 맞게 구현되어 있음.

**Comment by MoohyunSong** [comment]
#2 #17 #16 #18 에서 세부적으로 트래킹하겠습니다.
