### ISSUE TITLE
tf serving 코드 arm 버전으로 빌드하기

### ISSUE THREAD

**Issue by kh3654po** [ddps-lab/tfserving-inference#48]
- https://github.com/ARM-software/Tool-Solutions/
- https://github.com/tensorflow/serving
위 두개를 참고

**Comment by kh3654po** [comment]
무현님과 같이 빌드완료했습니다. 
해당 내용은 https://github.com/ddps-lab/kubevc/issues/36에 정리되었습니다.
진행과정은 https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel을 참고하여 관련 패키지와 bazel 6.1.0을 설치하고 tfserving code를 build하였습니다.
aws arm인스턴스를 실행하고 빌드할 때 option으로 --config=nativeopt를 사용하여 arm아키텍처에 맞게 빌드되도록 하였습니다.
이 실행파일을 가지고 xavier에서 테스트 해보겠습니다.

**Comment by kh3654po** [comment]
테스트는 빌드한 바이너리 파일을 xavier에 가져와 실행해보았는데 빌드할 때 우분투 20.04 환경으로 빌드하여 18.04인 xavier에서는 실행되지 않았습니다. 18.04버전으로 새롭게 Dockerfile을 만들고 docker image를 만들어 테스트를 다시 진행해보겠습니다.

**Comment by hyu-leeky** [comment]
오케이. 석현아 큰 허들을 하나 넘은듯 하다. xavier 에서 동작하게끔 환경 준비해서 진행해보자.
