### ISSUE TITLE
tf serving을 통해 한 컨테이너 위에서 여러 모델 serving 해보기

### ISSUE THREAD

**Issue by kh3654po** [ddps-lab/tfserving-inference#5]
현재는 하나씩만 serving 하고 있는데 여러 모델을 serving 해보려함

**Comment by hyu-leeky** [comment]
여러 모델 서빙 관련 한 내용을 포함한 이슈 - https://github.com/ddps-lab/research-issues/issues/227

**Comment by kh3654po** [comment]
한 컨테이너에서 여러 모델이 serving되는것을 확인했으므로 이 이슈는  close 하겠습니다.
